stages:
  - test

mix_test:
  stage: test
  image: elixir:1.8.1-alpine
  variables:
    MIX_ENV: test
    TWEETER_DATABASE_URL: ecto://postgres:postgres@postgres/tweeter_test
    POSTGRES_DB: tweeter_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    ELIXIR_LOGGER_LEVEL: trace
    TWEETER_EVENTSTORE: eventstore-eventstore
  services:
    - postgres:10.5-alpine
    - rabbitmq:3.7.15-alpine
    - eventstore/eventstore:release-4.1.2
  script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get && mix deps.compile
    - mix test
