version: "2"
services:
  postgres:
    image: postgres:10.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tweeter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  eventstore:
    image: eventstore/eventstore:release-4.1.2
    ports:
      - 1113:1113
      - 2113:2113
